name: 'Upload Test Logs'
description: 'Copy and upload test logs'

runs:
  using: "composite"
  steps:
    - name: Copy logs to hack permission
      if: always()
      shell: bash
      run: |
        if [ ! -d "/tmp/tidb_cdc_test" ]; then
          echo "Directory /tmp/tidb_cdc_test does not exist, skipping log collection"
          exit 0
        fi
        DIR=$(sudo find /tmp/tidb_cdc_test/ -type d -name 'cdc_data*' -exec dirname {} \; | tail -n 1)
        echo "Found the last dir: $DIR"
        [ -z "$DIR" ] && exit 0
        CASE=$(basename $DIR)
        mkdir -p ./logs/$CASE
        cat $DIR/stdout.log || true
        tail -n 10 $DIR/cdc.log || true
        sudo cp -r -L $DIR/*.log ./logs/$CASE/ || true
        sudo cp -r -L $DIR/sync_diff ./logs/$CASE/ || true
        sudo chown -R runner ./logs 
        sudo tar -czvf ./logs.tar.gz ./logs

    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ inputs.log-name || 'test-logs' }}
        path: |
          ./logs.tar.gz

inputs:
  log-name:
    description: 'Name of the log artifact'
    required: false