// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/keyspace/keyspace_manager.go

// Package keyspace is a generated GoMock package.
package keyspace

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	keyspacepb "github.com/pingcap/kvproto/pkg/keyspacepb"
	kv "github.com/pingcap/tidb/pkg/kv"
)

// MockKeyspaceManager is a mock of KeyspaceManager interface.
type MockKeyspaceManager struct {
	ctrl     *gomock.Controller
	recorder *MockKeyspaceManagerMockRecorder
}

// MockKeyspaceManagerMockRecorder is the mock recorder for MockKeyspaceManager.
type MockKeyspaceManagerMockRecorder struct {
	mock *MockKeyspaceManager
}

// NewMockKeyspaceManager creates a new mock instance.
func NewMockKeyspaceManager(ctrl *gomock.Controller) *MockKeyspaceManager {
	mock := &MockKeyspaceManager{ctrl: ctrl}
	mock.recorder = &MockKeyspaceManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyspaceManager) EXPECT() *MockKeyspaceManagerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockKeyspaceManager) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockKeyspaceManagerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockKeyspaceManager)(nil).Close))
}

// GetKeyspaceByID mocks base method.
func (m *MockKeyspaceManager) GetKeyspaceByID(ctx context.Context, keyspaceID uint32) (*keyspacepb.KeyspaceMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeyspaceByID", ctx, keyspaceID)
	ret0, _ := ret[0].(*keyspacepb.KeyspaceMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeyspaceByID indicates an expected call of GetKeyspaceByID.
func (mr *MockKeyspaceManagerMockRecorder) GetKeyspaceByID(ctx, keyspaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyspaceByID", reflect.TypeOf((*MockKeyspaceManager)(nil).GetKeyspaceByID), ctx, keyspaceID)
}

// GetStorage mocks base method.
func (m *MockKeyspaceManager) GetStorage(keyspace string) (kv.Storage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStorage", keyspace)
	ret0, _ := ret[0].(kv.Storage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStorage indicates an expected call of GetStorage.
func (mr *MockKeyspaceManagerMockRecorder) GetStorage(keyspace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStorage", reflect.TypeOf((*MockKeyspaceManager)(nil).GetStorage), keyspace)
}

// LoadKeyspace mocks base method.
func (m *MockKeyspaceManager) LoadKeyspace(ctx context.Context, keyspace string) (*keyspacepb.KeyspaceMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadKeyspace", ctx, keyspace)
	ret0, _ := ret[0].(*keyspacepb.KeyspaceMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadKeyspace indicates an expected call of LoadKeyspace.
func (mr *MockKeyspaceManagerMockRecorder) LoadKeyspace(ctx, keyspace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadKeyspace", reflect.TypeOf((*MockKeyspaceManager)(nil).LoadKeyspace), ctx, keyspace)
}
