// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/api/v2/api_client.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	rest "github.com/pingcap/ticdc/pkg/api/internal/rest"
	v2 "github.com/pingcap/ticdc/pkg/api/v2"
)

// MockAPIV2Interface is a mock of APIV2Interface interface.
type MockAPIV2Interface struct {
	ctrl     *gomock.Controller
	recorder *MockAPIV2InterfaceMockRecorder
}

// MockAPIV2InterfaceMockRecorder is the mock recorder for MockAPIV2Interface.
type MockAPIV2InterfaceMockRecorder struct {
	mock *MockAPIV2Interface
}

// NewMockAPIV2Interface creates a new mock instance.
func NewMockAPIV2Interface(ctrl *gomock.Controller) *MockAPIV2Interface {
	mock := &MockAPIV2Interface{ctrl: ctrl}
	mock.recorder = &MockAPIV2InterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIV2Interface) EXPECT() *MockAPIV2InterfaceMockRecorder {
	return m.recorder
}

// Captures mocks base method.
func (m *MockAPIV2Interface) Captures() v2.CaptureInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Captures")
	ret0, _ := ret[0].(v2.CaptureInterface)
	return ret0
}

// Captures indicates an expected call of Captures.
func (mr *MockAPIV2InterfaceMockRecorder) Captures() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Captures", reflect.TypeOf((*MockAPIV2Interface)(nil).Captures))
}

// Changefeeds mocks base method.
func (m *MockAPIV2Interface) Changefeeds() v2.ChangefeedInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Changefeeds")
	ret0, _ := ret[0].(v2.ChangefeedInterface)
	return ret0
}

// Changefeeds indicates an expected call of Changefeeds.
func (mr *MockAPIV2InterfaceMockRecorder) Changefeeds() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Changefeeds", reflect.TypeOf((*MockAPIV2Interface)(nil).Changefeeds))
}

// RESTClient mocks base method.
func (m *MockAPIV2Interface) RESTClient() rest.CDCRESTInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RESTClient")
	ret0, _ := ret[0].(rest.CDCRESTInterface)
	return ret0
}

// RESTClient indicates an expected call of RESTClient.
func (mr *MockAPIV2InterfaceMockRecorder) RESTClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RESTClient", reflect.TypeOf((*MockAPIV2Interface)(nil).RESTClient))
}

// Status mocks base method.
func (m *MockAPIV2Interface) Status() v2.StatusInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(v2.StatusInterface)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockAPIV2InterfaceMockRecorder) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockAPIV2Interface)(nil).Status))
}

// Tso mocks base method.
func (m *MockAPIV2Interface) Tso() v2.TsoInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tso")
	ret0, _ := ret[0].(v2.TsoInterface)
	return ret0
}

// Tso indicates an expected call of Tso.
func (mr *MockAPIV2InterfaceMockRecorder) Tso() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tso", reflect.TypeOf((*MockAPIV2Interface)(nil).Tso))
}

// Unsafe mocks base method.
func (m *MockAPIV2Interface) Unsafe() v2.UnsafeInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unsafe")
	ret0, _ := ret[0].(v2.UnsafeInterface)
	return ret0
}

// Unsafe indicates an expected call of Unsafe.
func (mr *MockAPIV2InterfaceMockRecorder) Unsafe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsafe", reflect.TypeOf((*MockAPIV2Interface)(nil).Unsafe))
}
