// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/sink/kafka/admin_client.go

// Package kafka is a generated GoMock package.
package kafka

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAdminClient is a mock of AdminClient interface.
type MockAdminClient struct {
	ctrl     *gomock.Controller
	recorder *MockAdminClientMockRecorder
}

// MockAdminClientMockRecorder is the mock recorder for MockAdminClient.
type MockAdminClientMockRecorder struct {
	mock *MockAdminClient
}

// NewMockAdminClient creates a new mock instance.
func NewMockAdminClient(ctrl *gomock.Controller) *MockAdminClient {
	mock := &MockAdminClient{ctrl: ctrl}
	mock.recorder = &MockAdminClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminClient) EXPECT() *MockAdminClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockAdminClient) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockAdminClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAdminClient)(nil).Close))
}

// CreateTopic mocks base method.
func (m *MockAdminClient) CreateTopic(detail *TopicDetail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTopic", detail)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTopic indicates an expected call of CreateTopic.
func (mr *MockAdminClientMockRecorder) CreateTopic(detail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTopic", reflect.TypeOf((*MockAdminClient)(nil).CreateTopic), detail)
}

// GetAllBrokers mocks base method.
func (m *MockAdminClient) GetAllBrokers() []Broker {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBrokers")
	ret0, _ := ret[0].([]Broker)
	return ret0
}

// GetAllBrokers indicates an expected call of GetAllBrokers.
func (mr *MockAdminClientMockRecorder) GetAllBrokers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBrokers", reflect.TypeOf((*MockAdminClient)(nil).GetAllBrokers))
}

// GetBrokerConfig mocks base method.
func (m *MockAdminClient) GetBrokerConfig(configName string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBrokerConfig", configName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBrokerConfig indicates an expected call of GetBrokerConfig.
func (mr *MockAdminClientMockRecorder) GetBrokerConfig(configName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBrokerConfig", reflect.TypeOf((*MockAdminClient)(nil).GetBrokerConfig), configName)
}

// GetTopicConfig mocks base method.
func (m *MockAdminClient) GetTopicConfig(topicName, configName string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopicConfig", topicName, configName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTopicConfig indicates an expected call of GetTopicConfig.
func (mr *MockAdminClientMockRecorder) GetTopicConfig(topicName, configName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopicConfig", reflect.TypeOf((*MockAdminClient)(nil).GetTopicConfig), topicName, configName)
}

// GetTopicsMeta mocks base method.
func (m *MockAdminClient) GetTopicsMeta(topics []string, ignoreTopicError bool) (map[string]TopicDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopicsMeta", topics, ignoreTopicError)
	ret0, _ := ret[0].(map[string]TopicDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopicsMeta indicates an expected call of GetTopicsMeta.
func (mr *MockAdminClientMockRecorder) GetTopicsMeta(topics, ignoreTopicError interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopicsMeta", reflect.TypeOf((*MockAdminClient)(nil).GetTopicsMeta), topics, ignoreTopicError)
}

// GetTopicsPartitionsNum mocks base method.
func (m *MockAdminClient) GetTopicsPartitionsNum(topics []string) (map[string]int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopicsPartitionsNum", topics)
	ret0, _ := ret[0].(map[string]int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopicsPartitionsNum indicates an expected call of GetTopicsPartitionsNum.
func (mr *MockAdminClientMockRecorder) GetTopicsPartitionsNum(topics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopicsPartitionsNum", reflect.TypeOf((*MockAdminClient)(nil).GetTopicsPartitionsNum), topics)
}
