// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/sink/kafka/cluster_admin_client.go

// Package kafka is a generated GoMock package.
package kafka

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockClusterAdminClient is a mock of ClusterAdminClient interface.
type MockClusterAdminClient struct {
	ctrl     *gomock.Controller
	recorder *MockClusterAdminClientMockRecorder
}

// MockClusterAdminClientMockRecorder is the mock recorder for MockClusterAdminClient.
type MockClusterAdminClientMockRecorder struct {
	mock *MockClusterAdminClient
}

// NewMockClusterAdminClient creates a new mock instance.
func NewMockClusterAdminClient(ctrl *gomock.Controller) *MockClusterAdminClient {
	mock := &MockClusterAdminClient{ctrl: ctrl}
	mock.recorder = &MockClusterAdminClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterAdminClient) EXPECT() *MockClusterAdminClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockClusterAdminClient) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockClusterAdminClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClusterAdminClient)(nil).Close))
}

// CreateTopic mocks base method.
func (m *MockClusterAdminClient) CreateTopic(detail *TopicDetail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTopic", detail)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTopic indicates an expected call of CreateTopic.
func (mr *MockClusterAdminClientMockRecorder) CreateTopic(detail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTopic", reflect.TypeOf((*MockClusterAdminClient)(nil).CreateTopic), detail)
}

// GetAllBrokers mocks base method.
func (m *MockClusterAdminClient) GetAllBrokers() []Broker {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBrokers")
	ret0, _ := ret[0].([]Broker)
	return ret0
}

// GetAllBrokers indicates an expected call of GetAllBrokers.
func (mr *MockClusterAdminClientMockRecorder) GetAllBrokers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBrokers", reflect.TypeOf((*MockClusterAdminClient)(nil).GetAllBrokers))
}

// GetBrokerConfig mocks base method.
func (m *MockClusterAdminClient) GetBrokerConfig(configName string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBrokerConfig", configName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBrokerConfig indicates an expected call of GetBrokerConfig.
func (mr *MockClusterAdminClientMockRecorder) GetBrokerConfig(configName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBrokerConfig", reflect.TypeOf((*MockClusterAdminClient)(nil).GetBrokerConfig), configName)
}

// GetTopicConfig mocks base method.
func (m *MockClusterAdminClient) GetTopicConfig(topicName, configName string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopicConfig", topicName, configName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTopicConfig indicates an expected call of GetTopicConfig.
func (mr *MockClusterAdminClientMockRecorder) GetTopicConfig(topicName, configName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopicConfig", reflect.TypeOf((*MockClusterAdminClient)(nil).GetTopicConfig), topicName, configName)
}

// GetTopicsMeta mocks base method.
func (m *MockClusterAdminClient) GetTopicsMeta(topics []string, ignoreTopicError bool) (map[string]TopicDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopicsMeta", topics, ignoreTopicError)
	ret0, _ := ret[0].(map[string]TopicDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopicsMeta indicates an expected call of GetTopicsMeta.
func (mr *MockClusterAdminClientMockRecorder) GetTopicsMeta(topics, ignoreTopicError interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopicsMeta", reflect.TypeOf((*MockClusterAdminClient)(nil).GetTopicsMeta), topics, ignoreTopicError)
}

// GetTopicsPartitionsNum mocks base method.
func (m *MockClusterAdminClient) GetTopicsPartitionsNum(topics []string) (map[string]int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopicsPartitionsNum", topics)
	ret0, _ := ret[0].(map[string]int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopicsPartitionsNum indicates an expected call of GetTopicsPartitionsNum.
func (mr *MockClusterAdminClientMockRecorder) GetTopicsPartitionsNum(topics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopicsPartitionsNum", reflect.TypeOf((*MockClusterAdminClient)(nil).GetTopicsPartitionsNum), topics)
}
