#!/bin/bash

set -eu
OUT_DIR=/tmp/tidb_cdc_test

if grep -Fq "$1" "$OUT_DIR/sql_res.$TEST_NAME.log"; then
	echo "TEST FAILED: OUTPUT CONTAINS '$1'"
	echo "____________________________________"
	cat "$OUT_DIR/sql_res.$TEST_NAME.log"
	echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
	exit 1
fi
