#!/bin/bash

set -eu
OUT_DIR=/tmp/tidb_cdc_test
LOG_FILE="$OUT_DIR/$TEST_NAME/sql_res.$TEST_NAME.log"

if grep -Fq "$1" "$LOG_FILE"; then
	echo "TEST FAILED: OUTPUT CONTAINS '$1'"
	echo "____________________________________"
	cat "$LOG_FILE"
	echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
	exit 1
fi
