#!/bin/bash
# parameter 1: work directory
WORK_DIR=$1

set +e

## check data race
if [ ! -f $WORK_DIR/stdout.log ]; then
	exit 0
fi

grep -q -i 'DATA RACE' $WORK_DIR/stdout.log

if [ $? -eq 0 ]; then
	echo "found DATA RACE, please check the logs"
	exit 1
else
	exit 0
fi
