#!/bin/bash
# parameter 1: work directory
WORK_DIR=$1

set +e

# find some file and change them to .log so the ci plugin will collect them
find $WORK_DIR -type f -name "*.txt" -o -name "*sql*" -o -name "*summary*" -o -name "*.json" -o -name "*.index" -o -name "metadata" -print0 | while IFS= read -r -d '' file; do
	if [[ -f "$file" ]]; then
		mv "$file" "${file%.txt}.log" 2>/dev/null || true
	fi
done
