#!/bin/bash

# cdc server is ran by binary cdc.test, kill cdc server first to avoid too much
# noise in cdc logs.

PKILL="killall -q -w -s 9 "
if [ "$(uname)" == "Darwin" ]; then
	PKILL="pkill -9 "
fi

${PKILL} cdc.test || true
${PKILL} cdc || true
${PKILL} cdc_kafka_consumer || true
${PKILL} cdc_storage_consumer || true
${PKILL} tidb-server || true
${PKILL} tikv-server || true
${PKILL} tiflash || true
${PKILL} flash_cluster_manager || true
${PKILL} pd-server || true
${PKILL} oauth_server || true
${PKILL} minio || true
${PKILL} tikv-worker || true

CUR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
source $CUR/../_utils/test_prepare

kill -9 $(lsof -i tcp:${UP_TIDB_PORT} -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:${UP_TIDB_OTHER_PORT} -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:${UP_TIDB_STATUS} -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:${UP_TIDB_SYSTEM_PORT} -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:${UP_TIDB_SYSTEM_STATUS} -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:${UP_TIDB_OTHER_STATUS} -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:${DOWN_TIDB_SYSTEM_PORT} -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:${DOWN_TIDB_SYSTEM_STATUS} -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:${DOWN_TIDB_PORT} -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:${DOWN_TIDB_STATUS} -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:${UP_PD_PORT_1} -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:${UP_PD_PEER_PORT_1} -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:${UP_PD_PORT_2} -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:${UP_PD_PEER_PORT_2} -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:${UP_PD_PORT_3} -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:${UP_PD_PEER_PORT_3} -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:${DOWN_PD_PORT} -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:${DOWN_PD_PEER_PORT} -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:${UP_TIKV_PORT_1} -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:${UP_TIKV_STATUS_PORT_1} -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:${UP_TIKV_PORT_2} -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:${UP_TIKV_STATUS_PORT_2} -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:${UP_TIKV_PORT_3} -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:${UP_TIKV_STATUS_PORT_3} -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:${DOWN_TIKV_PORT} -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:${DOWN_TIKV_STATUS_PORT} -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:${UP_TIKV_WORKER_PORT} -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:${DOWN_TIKV_WORKER_PORT} -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:9500 -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:17000 -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:6650 -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:6651 -t 2>/dev/null) &>/dev/null || true
kill -9 $(lsof -i tcp:9096 -t 2>/dev/null) &>/dev/null || true

if [ "$NEXT_GEN" = 1 ]; then
	if [[ -z "$TEST_NAME" || -z "$TEST_OUT_DATA_DIR" ]]; then
		echo "Error: TEST_NAME and TEST_OUT_DATA_DIR must be set for next-gen cleanup." >&2
		exit 0
	fi
	CASE_DIR="$CUR/../$TEST_NAME"
	TEST_DATA_DIR="$CASE_DIR/$TEST_OUT_DATA_DIR"
	rm -rf "$TEST_DATA_DIR"
fi
